import { Profile } from "./types";

export const mockProfiles: Profile[] = [
  {
    id: "1",
    first_name: "さくら",
    last_name: "田中",
    nickname: "さくらちゃん",
    name_reading: "サクラ",
    age: 25,
    gender: "female",
    city: "Tokyo",
    avatar_url: "https://images.unsplash.com/photo-1494790108755-2616b612b742?w=400&h=400&fit=crop&crop=face",
    description: "こんにちは！よろしくお願いします。",
    nationality: "JP",
    is_online: true,
    updated_at: null,
  },
  {
    id: "2",
    first_name: "あやか",
    last_name: "佐藤",
    nickname: "あやか",
    name_reading: "アヤカ",
    age: 29,
    gender: "female",
    city: "Osaka",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    description: "大阪出身です。よろしくお願いします！",
    nationality: "JP",
    is_online: false,
    updated_at: null,
  },
  {
    id: "3",
    first_name: "ゆい",
    last_name: "鈴木",
    nickname: "ゆいちゃん",
    name_reading: "ユイ",
    age: 27,
    gender: "female",
    city: "Kyoto",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    description: "京都の美しい街が大好きです。",
    nationality: "JP",
    is_online: true,
    updated_at: null,
  },
  {
    id: "4",
    first_name: "みか",
    last_name: "山田",
    nickname: "みか",
    name_reading: "ミカ",
    age: 26,
    gender: "female",
    city: "Yokohama",
    avatar_url: "https://images.unsplash.com/photo-1521577352947-9bb58764b69a?w=400&h=400&fit=crop&crop=face",
    description: "横浜でお仕事しています。",
    nationality: "JP",
    is_online: false,
    updated_at: null,
  },
  {
    id: "5",
    first_name: "えみ",
    last_name: "伊藤",
    nickname: "えみっち",
    name_reading: "エミ",
    age: 24,
    gender: "female",
    city: "Nagoya",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face",
    description: "名古屋のグルメが大好き！",
    nationality: "JP",
    is_online: true,
    updated_at: null,
  },
  {
    id: "6",
    first_name: "りな",
    last_name: "高橋",
    nickname: "りな",
    name_reading: "リナ",
    age: 31,
    gender: "female",
    city: "Kobe",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    description: "神戸でのんびり暮らしています。",
    nationality: "JP",
    is_online: false,
    updated_at: null,
  },
  {
    id: "7",
    first_name: "まい",
    last_name: "松本",
    nickname: "まいまい",
    name_reading: "マイ",
    age: 26,
    gender: "female",
    city: "Fukuoka",
    avatar_url: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=400&fit=crop&crop=face",
    description: "福岡出身です。明太子が大好き！",
    nationality: "JP",
    is_online: false,
    updated_at: null,
  },
  {
    id: "8",
    first_name: "なな",
    last_name: "田中",
    nickname: "なな",
    name_reading: "ナナ",
    age: 25,
    gender: "female",
    city: "Sapporo",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop&crop=face",
    description: "北海道の自然が大好きです。",
    nationality: "JP",
    is_online: true,
    updated_at: null,
  },
];
